### ISSUE TITLE
Interaktiivne ehk rakendusesisene abiinfo (1.6)

### ISSUE THREAD

**Issue by taneltomson** [taneltomson/vaitlusveeb#11]

**Comment by ainika** [comment]
Ma teeks nt taimerile juhendi? Stiilis mis variandid ja kellele? Väike button ja siis kiri sinna juurde?

**Comment by TuuleS** [comment]
See tekst oleneb sellest, kui palju sa taimerit teed. Nt
"Esimesed kuus kõnet kestavad 6 minutit, nende vahel on 1 minut mõtlemiseks. Kaks kokkuvõtvat kõnet kestavad kolm minutit. Kasuta nende aegade jälgimiseks just seda taimerit!"

**Comment by TuuleS** [comment]
Tegin /index.php/register lehele ka selle info ära
